language: c 

addons:
  apt:
    packages:
    - gcc-arm-none-eabi 
    - libsdl1.2-dev
    - python-imaging
install: 
  # check it worked  
  - arm-none-eabi-gcc --version 
  - gcc --version
  - python -c "from PIL import Image"
  - echo $TRAVIS_BUILD_DIR
script:
  - "make && make test"

after_script:

env:
  - BITBOX=/home/travis/build/makapuf/bitbox
