# use distro trusty
sudo: required
dist: trusty

language: c 
before_script:
  ## Install mainline ARM toolchain.  gcc-arm-none-eabi is available
  ## in Ubuntu >= 14.04, just use it 
  ## (from kontiki)
  - sudo add-apt-repository -y ppa:terry.guo/gcc-arm-embedded
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
  - sudo apt-get -qq install gcc-arm-none-eabi libsdl1.2-dev python-imaging


  # check it worked
  - arm-none-eabi-gcc --version 
  - gcc --version
script:
  - "make && make alltest"

after_script:

env:
  - BITBOX=../
