language: c 
sudo: false
dist: trusty
addons:
  apt:
    packages:
    - gcc-arm-none-eabi 
    - libnewlib-arm-none-eabi
    - libnewlib-dev
    - libsdl1.2-dev
    - python-pil
install: 
  # check it worked  
  - arm-none-eabi-gcc --version 
  - gcc --version
  - python -c "help('modules')"
  - python -c "from PIL import Image"
script:
  - "make && make test"

env:
  - BITBOX=$TRAVIS_BUILD_DIR
