# use distro trusty
sudo: required
dist: trusty

language: c 
before_script:
  - sudo apt-get -qq update
  - sudo apt-get -qq install gcc-arm-none-eabi libsdl1.2-dev 
  - pip install Pillow
  # check it worked  
  - arm-none-eabi-gcc --version 
  - gcc --version
  - pip list 
  - python -c "from PIL import Image"
  
script:
  - "make && make test"

after_script:

env:
  - BITBOX=/home/travis/build/makapuf/bitbox
