# use distro trusty
sudo: required
dist: trusty

language: c 
before_script:
  - sudo apt-get -qq update
  - sudo apt-get -qq install gcc-arm-none-eabi libsdl1.2-dev python-pil


  # check it worked
  - arm-none-eabi-gcc --version 
  - gcc --version
script:
  - "make && make alltest"

after_script:

env:
  - BITBOX=../
