language: c #NOTE: this will set CC=gcc which might cause trouble
before_script:
  - sudo apt-get -qq update

  ## Install mainline ARM toolchain.  gcc-arm-none-eabi is available
  ## in Ubuntu >= 14.04, but this external PPA is needed for 12.04.
  ## (from kontiki)
  - sudo add-apt-repository -y ppa:terry.guo/gcc-arm-embedded
  - sudo apt-get -qq update
  - sudo apt-get -qq install gcc-arm-none-eabi srecord
  - arm-none-eabi-gcc --version 

script:
  - "cd crappy && make"

after_script:


env:
  - BITBOX=../