# use distro trusty
sudo: required
dist: trusty

language: c 
before_script:
  - sudo apt-get -qq update
  - sudo apt-get -qq install gcc-arm-none-eabi libsdl1.2-dev 

  - pip install Pillow
  - ls /usr/lib/python2.7/dist-packages/PIL/
  # check it worked  
  - arm-none-eabi-gcc --version 
  - gcc --version
  - pip list 
  - python -c "import Image"
  
script:
  - "make && make alltest"

after_script:

env:
  - BITBOX=../
